package modelo;

// Generated 10/06/2016 12:39:05 PM by Hibernate Tools 3.4.0.CR1

import general.ManejarEntidades;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Cuentas generated by hbm2java
 */
public class Cuentas extends ManejarEntidades implements java.io.Serializable {

	private int id;
	private Moneda moneda;
	private String numeroCuenta;
	private String banco;
	private Double montoInicial;
	private Double montoActual;
	private String estatus;
	private Set ingresoses = new HashSet(0);
	private Set gastoses = new HashSet(0);
	private Set detalleCuentases = new HashSet(0);

	public Cuentas() {
	}

	public Cuentas(int id) {
		this.id = id;
	}

	public Cuentas(int id, Moneda moneda, String numeroCuenta, String banco,
			Double montoInicial, Double montoActual, String estatus,
			Set ingresoses, Set gastoses, Set detalleCuentases) {
		this.id = id;
		this.moneda = moneda;
		this.numeroCuenta = numeroCuenta;
		this.banco = banco;
		this.montoInicial = montoInicial;
		this.montoActual = montoActual;
		this.estatus = estatus;
		this.ingresoses = ingresoses;
		this.gastoses = gastoses;
		this.detalleCuentases = detalleCuentases;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Moneda getMoneda() {
		return this.moneda;
	}

	public void setMoneda(Moneda moneda) {
		this.moneda = moneda;
	}

	public String getNumeroCuenta() {
		return this.numeroCuenta;
	}

	public void setNumeroCuenta(String numeroCuenta) {
		this.numeroCuenta = numeroCuenta;
	}

	public String getBanco() {
		return this.banco;
	}

	public void setBanco(String banco) {
		this.banco = banco;
	}

	public Double getMontoInicial() {
		return this.montoInicial;
	}

	public void setMontoInicial(Double montoInicial) {
		this.montoInicial = montoInicial;
	}

	public Double getMontoActual() {
		return this.montoActual;
	}

	public void setMontoActual(Double montoActual) {
		this.montoActual = montoActual;
	}

	public String getEstatus() {
		return this.estatus;
	}

	public void setEstatus(String estatus) {
		this.estatus = estatus;
	}

	public Set getIngresoses() {
		return this.ingresoses;
	}

	public void setIngresoses(Set ingresoses) {
		this.ingresoses = ingresoses;
	}

	public Set getGastoses() {
		return this.gastoses;
	}

	public void setGastoses(Set gastoses) {
		this.gastoses = gastoses;
	}

	public Set getDetalleCuentases() {
		return this.detalleCuentases;
	}

	public void setDetalleCuentases(Set detalleCuentases) {
		this.detalleCuentases = detalleCuentases;
	}
	
	public List<Object[]> consultarCuentas(){
		List<Object[]> lista = null;
		String sql = "";
		try{
			sql = "select a.id, a.numeroCuenta, a.banco, a.montoActual from Cuentas a where a.estatus='AC' order by 2 ";
			lista = (List<Object[]>) this.ConsultarLista(sql);
		} catch (Exception ex) {
			System.out.println("ERROR en consultarCuentas "+ex.getMessage());
		}
		return lista;
		
	}
	
	public List<Object[]> consultarCuenta(Integer id){
		List<Object[]> lista = null;
		String sql = "";
		try{
			sql = "select a.numeroCuenta, a.banco, a.montoInicial, a.moneda.id, a.montoActual from Cuentas a where a.estatus='AC' and a.id="+id+" order by 2";
			lista = (List<Object[]>) this.Consultar(sql);
		} catch (Exception ex) {
			System.out.println("ERROR en consultarCuenta "+ex.getMessage());
		}
		return lista;
		
	}
	
	public List<Object[]> saldoBolivares(){
		List<Object[]> lista = null;
		String sql = "";
		try{
			sql = "select a.moneda.id, sum(a.montoActual) from Cuentas a where a.estatus='AC' and a.moneda.id=1 group by 1";
			lista = (List<Object[]>) this.Consultar(sql);
		} catch (Exception ex) {
			System.out.println("ERROR en saldoBolivares "+ex.getMessage());
		}
		return lista;
		
	}
	
	public List<Object[]> saldoDolares(){
		List<Object[]> lista = null;
		String sql = "";
		try{
			sql = "select a.moneda.id, sum(a.montoActual) from Cuentas a where a.estatus='AC' and a.moneda.id=2 group by 1";
			lista = (List<Object[]>) this.Consultar(sql);
		} catch (Exception ex) {
			System.out.println("ERROR en saldoBolivares "+ex.getMessage());
		}
		return lista;
		
	}
	
	public List<Object[]> efectivoDolares(){
		List<Object[]> lista = null;
		String sql = "";
		try{
			sql = "select a.moneda.id, sum(a.montoActual) from Cuentas a where a.estatus='AC' and a.moneda.id=2 and a.numeroCuenta='Efectivo Dolares' group by 1";
			lista = (List<Object[]>) this.Consultar(sql);
		} catch (Exception ex) {
			System.out.println("ERROR en saldoBolivares "+ex.getMessage());
		}
		return lista;
		
	}
	
	public List<Object[]> efectivoBolivares(){
		List<Object[]> lista = null;
		String sql = "";
		try{
			sql = "select a.moneda.id, sum(a.montoActual) from Cuentas a where a.estatus='AC' and a.moneda.id=1 and a.numeroCuenta='Efectivo Bolivares' group by 1";
			lista = (List<Object[]>) this.Consultar(sql);
		} catch (Exception ex) {
			System.out.println("ERROR en saldoBolivares "+ex.getMessage());
		}
		return lista;
		
	}

}
