package modelo;

// Generated 10/06/2016 12:39:05 PM by Hibernate Tools 3.4.0.CR1

import general.ManejarEntidades;

import java.util.Date;
import java.util.List;

/**
 * Gastos generated by hbm2java
 */
public class Gastos extends ManejarEntidades implements java.io.Serializable {

	private int id;
	private Cuentas cuentas;
	private String descripcion;
	private Double monto;
	private Date fecha;
	private String estatus;

	public Gastos() {
	}

	public Gastos(int id) {
		this.id = id;
	}

	public Gastos(int id, Cuentas cuentas, String descripcion, Double monto,
			Date fecha, String estatus) {
		this.id = id;
		this.cuentas = cuentas;
		this.descripcion = descripcion;
		this.monto = monto;
		this.fecha = fecha;
		this.estatus = estatus;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Cuentas getCuentas() {
		return this.cuentas;
	}

	public void setCuentas(Cuentas cuentas) {
		this.cuentas = cuentas;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Double getMonto() {
		return this.monto;
	}

	public void setMonto(Double monto) {
		this.monto = monto;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getEstatus() {
		return this.estatus;
	}

	public void setEstatus(String estatus) {
		this.estatus = estatus;
	}
	
	public List<Object[]> consultarGasto(Integer id){
		List<Object[]> lista = null;
		String sql = "";
		try{
			sql = "select a.id, a.monto from Gastos a where a.id="+id+"  ";
			lista = (List<Object[]>) this.Consultar(sql);
		} catch (Exception ex) {
			System.out.println("ERROR en consultarGasto "+ex.getMessage());
		}
		return lista;
		
	}
	
	public List<Object[]> consultarGastos(){
		List<Object[]> lista = null;
		String sql = "";
		try{
			sql = "select a.id, a.fecha, a.cuentas.banco, a.descripcion, a.monto from Gastos a " +
					"order by 1 desc";
			lista = (List<Object[]>) this.ConsultarLista(sql);
		} catch (Exception ex) {
			System.out.println("ERROR en consultarGastos "+ex.getMessage());
		}
		return lista;
		
	}

}
