package modelo;

// Generated 14/06/2016 08:10:18 AM by Hibernate Tools 3.4.0.CR1

import general.ManejarEntidades;

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Ingresos generated by hbm2java
 */
public class Ingresos extends ManejarEntidades implements java.io.Serializable {

	private int id;
	private Cuentas cuentas;
	private String descripcion;
	private Double monto;
	private String estatus;
	private Date fecha;
	private Set detalleCuentases = new HashSet(0);

	public Ingresos() {
	}

	public Ingresos(int id) {
		this.id = id;
	}

	public Ingresos(int id, Cuentas cuentas, String descripcion, Double monto,
			String estatus, Date fecha, Set detalleCuentases) {
		this.id = id;
		this.cuentas = cuentas;
		this.descripcion = descripcion;
		this.monto = monto;
		this.estatus = estatus;
		this.fecha = fecha;
		this.detalleCuentases = detalleCuentases;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Cuentas getCuentas() {
		return this.cuentas;
	}

	public void setCuentas(Cuentas cuentas) {
		this.cuentas = cuentas;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Double getMonto() {
		return this.monto;
	}

	public void setMonto(Double monto) {
		this.monto = monto;
	}

	public String getEstatus() {
		return this.estatus;
	}

	public void setEstatus(String estatus) {
		this.estatus = estatus;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Set getDetalleCuentases() {
		return this.detalleCuentases;
	}

	public void setDetalleCuentases(Set detalleCuentases) {
		this.detalleCuentases = detalleCuentases;
	}

	public List<Object[]> consultarIngreso(Integer id){
		List<Object[]> lista = null;
		String sql = "";
		try{
			sql = "select a.id, a.monto from Ingresos a where a.id="+id+"  ";
			lista = (List<Object[]>) this.Consultar(sql);
		} catch (Exception ex) {
			System.out.println("ERROR en consultarIngreso "+ex.getMessage());
		}
		return lista;
		
	}
	
	public List<Object[]> consultarIngresos(){
		List<Object[]> lista = null;
		String sql = "";
		try{
			sql = "select a.id, a.fecha, a.cuentas.banco, a.descripcion, a.monto from Ingresos a " +
					"order by 1 desc";
			lista = (List<Object[]>) this.ConsultarLista(sql);
		} catch (Exception ex) {
			System.out.println("ERROR en consultarIngresos "+ex.getMessage());
		}
		return lista;
		
	}
}
